title: "Blockchain Commons"
project: "Blockchain Commons"
description: "Supporting Blockchain and Internet Security & Infrastructure"
author: Blockchain Commons
email: info@BlockchainCommons.com
twitter_username: BlockchainCommons
github_username:  BlockchainCommons
show_downloads: false
encoding: UTF-8
kramdown:
  input: GFM
  hard_wrap: false
future: true
jailed: false
theme: jekyll-theme-primer
gfm_quirks: paragraph_end
